export const products = [
  {
    id: 1,
    date: "2026-08-29",
    name: "E-book นิทานก่อนนอนผจญภัย",
    description: "หนังสือนิทานภาพสีสันสดใส ช่วยเสริมสร้างจินตนาการสำหรับเด็ก",
    tag: "Ebook",
    tagColor: "bg-blue-100 text-blue-700",
    price: 150,
    quantity: 2048,
    rating: 4.8,
    reviews: 97,
    images: ["📚", "🧸", "✨", "📖"],
    details: {
      pages: "32 หน้า",
      format: "PDF, EPUB",
      language: "ไทย / English",
      suitableFor: "เด็กอายุ 3-8 ปี, ผู้ปกครอง",
      license: "Personal Use",
      software: "แอปอ่าน E-book ทั่วไป, iPad",
      lastUpdated: "ก.ค. 2025",
    },
  },
  {
    id: 2,
    date: "2026-08-29",
    name: "Digital Postcard Watercolor",
    description:
      "ชุดไฟล์การ์ดอวยพรที่ระลึก ลายสีน้ำสุดน่ารัก สามารถพิมพ์ใช้งานได้เลย",
    tag: "Souvenir",
    tagColor: "bg-orange-100 text-orange-700",
    price: 50,
    quantity: 1461,
    rating: 4.8,
    reviews: 134,
    images: ["🎁", "💌", "🌸", "🎨"],
    details: {
      quantity: "20 ลาย",
      format: "PNG พื้นหลังโปร่งใส (300 DPI)",
      resolution: "3000 x 3000 px",
      suitableFor: "งานแต่งงาน, การ์ดอวยพร, สินค้าที่ระลึก",
      license: "Personal & Commercial Use",
      usage: "พิมพ์, Digital Design",
      lastUpdated: "ก.ค. 2025",
    },
  },
  {
    id: 3,
    date: "2026-08-29",
    name: "E-book How To เริ่มต้นธุรกิจออนไลน์",
    description:
      "คู่มือฉบับจับมือทำ สอนปั้นแบรนด์และเปิดร้านออนไลน์ให้ยอดขายปัง",
    tag: "Ebook",
    tagColor: "bg-blue-100 text-blue-700",
    price: 290,
    quantity: 904,
    rating: 4.9,
    reviews: 155,
    images: ["📚", "💡", "📈", "🚀"],
    details: {
      pages: "120 หน้า",
      format: "PDF",
      language: "ไทย",
      suitableFor: "ผู้เริ่มต้นทำธุรกิจ, พ่อค้าแม่ค้าออนไลน์",
      license: "Personal Use",
      software: "แอปอ่าน PDF ทั่วไป",
      lastUpdated: "ส.ค. 2025",
    },
  },
  {
    id: 4,
    date: "2026-08-29",
    name: "Template ประกอบงาน Presentation",
    description:
      "เทมเพลตพรีเซนต์ระดับโปร สำหรับ PowerPoint และ Keynote พร้อมใช้งานทันที",
    tag: "Template",
    tagColor: "bg-purple-100 text-purple-700",
    price: 900,
    quantity: 500,
    rating: 4.9,
    reviews: 210,
    images: ["📄", "📊", "📈", "🗂️"],
    details: {
      slides: "50 สไลด์",
      format: "PPTX, KEY, Google Slides",
      suitableFor: "นักธุรกิจ, นักศึกษา, นักการตลาด",
      editability: "ปรับแต่งได้ทุกองค์ประกอบ",
      software: "PowerPoint, Keynote, Google Slides",
      colorScheme: "3 ชุดสี (Light, Dark, Colorful)",
      lastUpdated: "ส.ค. 2025",
    },
  },
  {
    id: 5,
    date: "2026-08-29",
    name: "Canva Planner Template",
    description: "แพลนเนอร์เทมเพลตดีไซน์มินิมอล สำหรับจัดการตารางชีวิตบน Canva",
    tag: "Template",
    tagColor: "bg-purple-100 text-purple-700",
    price: 150,
    quantity: 804,
    rating: 4.8,
    reviews: 112,
    images: ["📄", "📅", "📝", "✨"],
    details: {
      pages: "20 หน้า",
      format: "Canva Link",
      suitableFor: "นักเรียน, นักศึกษา, คนทำงาน",
      editability: "แก้ไขสี ฟอนต์ และข้อความได้อิสระ",
      software: "Canva (ใช้ฟรีได้)",
      platform: "Digital Planner, พิมพ์ใช้งาน",
      lastUpdated: "มิ.ย. 2025",
    },
  },
  {
    id: 6,
    date: "2026-08-29",
    name: "E-book นิยายสืบสวน: ปริศนาคฤหาสน์ซ่อนเงื่อน",
    description: "นิยายสืบสวนสอบสวนสุดระทึกขวัญ หักมุมทุกตอนจนวางไม่ลง",
    tag: "Ebook",
    tagColor: "bg-blue-100 text-blue-700",
    price: 250,
    quantity: 2048,
    rating: 4.6,
    reviews: 197,
    images: ["📚", "🕵️", "🔍", "🩸"],
    details: {
      pages: "250 หน้า",
      format: "PDF, EPUB, MOBI",
      language: "ไทย",
      suitableFor: "คนรักนิยายสืบสวน, วัยรุ่นและผู้ใหญ่",
      license: "Personal Use",
      software: "Kindle, Apple Books, Google Play Books",
      lastUpdated: "พ.ค. 2025",
    },
  },
  {
    id: 7,
    date: "2026-08-29",
    name: "ชุดการ์ดที่ระลึก สติกเกอร์ภาษาไทย",
    description:
      "ไฟล์การ์ดพร้อมสติกเกอร์น่ารัก สำหรับส่งเป็นของขวัญที่ระลึกในช่องทางแชท",
    tag: "Souvenir",
    tagColor: "bg-orange-100 text-orange-700",
    price: 250,
    quantity: 1704,
    rating: 4.6,
    reviews: 321,
    images: ["🎁", "😊", "🌟", "💌"],
    details: {
      quantity: "32 สติกเกอร์",
      format: "PNG พื้นหลังโปร่งใส",
      suitableFor: "LINE Official Account, ของที่ระลึกธุรกิจ",
      license: "Commercial Use",
      usage: "LINE, Telegram, พิมพ์สติกเกอร์",
      resolution: "370 x 320 px",
      lastUpdated: "ก.ค. 2025",
    },
  },
  {
    id: 8,
    date: "2026-08-29",
    name: "CV & Resume Template",
    description: "เทมเพลต Resume สมัครงานดีไซน์ทันสมัย แก้ไขได้อิสระใน Canva",
    tag: "Template",
    tagColor: "bg-purple-100 text-purple-700",
    price: 99,
    quantity: 1027,
    rating: 4.4,
    reviews: 64,
    images: ["📄", "👔", "💼", "📋"],
    details: {
      pages: "2 หน้า (CV + Cover Letter)",
      format: "Canva Link, PDF, DOCX",
      suitableFor: "ผู้หางาน, นักศึกษาจบใหม่, มืออาชีพ",
      editability: "แก้ไขสีและฟอนต์ได้อิสระ",
      software: "Canva (Free), Microsoft Word",
      colorScheme: "5 ชุดสี",
      lastUpdated: "ส.ค. 2025",
    },
  },
  {
    id: 9,
    date: "2026-08-29",
    name: "ชุดสกรีนเสื้อ T-shirt Design",
    description:
      "ลายสกรีนเสื้อกราฟิกเท่ๆ ไฟล์ Vector PNG พื้นหลังโปร่งใส พร้อมพิมพ์",
    tag: "T-shirt Design",
    tagColor: "bg-green-100 text-green-700",
    price: 150,
    quantity: 854,
    rating: 4.5,
    reviews: 73,
    images: ["👕", "🎨", "✏️", "🖌️"],
    details: {
      quantity: "10 ลาย",
      format: "AI, PNG (300 DPI) พื้นหลังโปร่งใส",
      printMethod: "Screen Printing, DTF, DTG, Sublimation",
      suitableFor: "โรงพิมพ์, ร้านสกรีนเสื้อ, ออกแบบเสื้อทีม",
      colors: "Single Color & Full Color",
      resolution: "4500 x 5400 px",
      lastUpdated: "มิ.ย. 2025",
    },
  },
  {
    id: 10,
    date: "2026-08-29",
    name: "Notion Daily Planner",
    description:
      "เทมเพลต Notion จัดการตารางงานรายวัน เพื่อเพิ่ม Productivity สูงสุด",
    tag: "Template",
    tagColor: "bg-purple-100 text-purple-700",
    price: 290,
    quantity: 504,
    rating: 4.9,
    reviews: 205,
    images: ["📄", "🗓️", "✅", "💻"],
    details: {
      features: "ระบบ To-Do List, Habit Tracker, สมุดบันทึก",
      format: "Notion Template Link",
      suitableFor: "คนวัยทำงาน, นักเรียน, Freelance",
      editability: "ปรับแต่ง Database และโครงสร้างได้ 100%",
      software: "Notion",
      platform: "Web, Mac, Windows, iOS, Android",
      lastUpdated: "ส.ค. 2025",
    },
  },
  {
    id: 11,
    date: "2026-08-29",
    name: "E-book How To จัดการการเงินส่วนบุคคล",
    description:
      "คู่มือเคล็ดลับบริหารเงินฉบับมนุษย์เงินเดือน ให้มีเงินเก็บหลักล้าน",
    tag: "Ebook",
    tagColor: "bg-blue-100 text-blue-700",
    price: 199,
    quantity: 1104,
    rating: 4.9,
    reviews: 242,
    images: ["📚", "💰", "📈", "🏦"],
    details: {
      pages: "150 หน้า",
      format: "PDF, EPUB",
      language: "ไทย",
      suitableFor: "พนักงานประจำ, วัยเริ่มทำงาน",
      license: "Personal Use",
      software: "แอปอ่าน E-book ทั่วไป",
      lastUpdated: "ก.ค. 2025",
    },
  },
  {
    id: 12,
    date: "2026-08-29",
    name: "Digital Postcard เทศกาลไทย",
    description:
      "ไฟล์การ์ดอวยพรของที่ระลึก 12 ลายเทศกาลไทย พร้อมส่งมอบความสุขให้คนพิเศษ",
    tag: "Souvenir",
    tagColor: "bg-orange-100 text-orange-700",
    price: 200,
    quantity: 1704,
    rating: 4.7,
    reviews: 89,
    images: ["🎁", "🏮", "🌺", "🎊"],
    details: {
      quantity: "12 ลาย (เทศกาลไทย)",
      format: "PNG, JPG (300 DPI)",
      resolution: "1748 x 1240 px (A5)",
      suitableFor: "ส่งอวยพร, โปสการ์ดออนไลน์, สิ่งพิมพ์",
      license: "Personal Use",
      usage: "ส่งทาง LINE, Email, พิมพ์จริง",
      lastUpdated: "พ.ค. 2025",
    },
  },
];

// export const tagEmoji = (tag) => {
//   if (tag === 'Ebook') return '📚';
//   if (tag === 'Template') return '📄';
//   if (tag === 'Souvenir') return '🎁';
//   return '👕';
// };
